const SUPABASE_URL='https://mjyuwmqnmzdhpvpnvsik.supabase.co';
const SUPABASE_KEY='sb_publishable_JeT3zymWaxbpQezfudnQWw_QLQvrLyw';
const db=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
const PUBLIC_URL='https://egbertomesquita-cmd.github.io/registro-atividades-decb/';
let session=null,profile=null,items=[],visitorMode=false;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const toast=(message,error=false)=>{const el=$('#toast');el.textContent=message;el.className=error?'show error':'show';setTimeout(()=>el.className='',3500)};
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const fmt=d=>new Date(d+'T12:00:00').toLocaleDateString('pt-BR');

$('#google-login').onclick=async()=>{const btn=$('#google-login');btn.disabled=true;try{const {error}=await db.auth.signInWithOAuth({provider:'google',options:{redirectTo:PUBLIC_URL}});if(error)throw error}catch(err){toast(err.message||'Não foi possível iniciar o acesso pelo Google.',true);btn.disabled=false}};

async function authorize(userSession){visitorMode=false;document.body.classList.remove('public-mode');session=userSession;const email=session.user.email.toLowerCase();const {data,error}=await db.from('authorized_users').select('full_name,is_admin,active').eq('email',email).maybeSingle();if(error||!data?.active){await db.auth.signOut();session=null;throw new Error('Este e-mail não está na lista de acesso do DECB.')}profile=data;$('#user-name').textContent=data.full_name;$('#user-email').textContent=email;$('#professor').value=data.full_name;$('#logout').textContent='Sair';$('#auth-view').classList.add('hidden');$('#app-view').classList.remove('hidden');await loadActivities();}

db.auth.onAuthStateChange(async(_event,newSession)=>{if(newSession){try{await authorize(newSession)}catch(err){toast(err.message,true)}}else if(!visitorMode){$('#app-view').classList.add('hidden');$('#auth-view').classList.remove('hidden')}});
$('#public-access').onclick=async()=>{visitorMode=true;session=null;profile=null;document.body.classList.add('public-mode');$('#user-name').textContent='Visitante';$('#user-email').textContent='Consulta pública';$('#logout').textContent='Voltar ao acesso';$('#observer-note').classList.remove('hidden');$('#auth-view').classList.add('hidden');$('#app-view').classList.remove('hidden');await loadActivities();showPage('activities')};
$('#logout').onclick=()=>{if(visitorMode){visitorMode=false;document.body.classList.remove('public-mode');$('#observer-note').classList.add('hidden');$('#app-view').classList.add('hidden');$('#auth-view').classList.remove('hidden');return}db.auth.signOut()};

function showPage(id){$$('.page').forEach(p=>p.classList.toggle('hidden',p.id!==id));$$('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===id));$('.sidebar').classList.remove('open');if(id==='register'){$('#date').value||=new Date().toISOString().slice(0,10);$('#professor').value=profile?.full_name||''}if(id==='reports')renderReport()}
$$('[data-view]').forEach(b=>b.onclick=()=>showPage(b.dataset.view));$$('[data-go]').forEach(b=>b.onclick=()=>showPage(b.dataset.go));$('#menu').onclick=()=>$('.sidebar').classList.toggle('open');

async function loadActivities(){const columns=visitorMode?'id,title,activity_type,activity_date,professor_name,description,participants,duration_hours,has_product,product_type':'*';const {data,error}=await db.from('activities').select(columns).order('activity_date',{ascending:false}).order('created_at',{ascending:false});if(error)return toast(visitorMode?'A consulta pública ainda não está disponível.':'Não foi possível carregar as atividades.',true);items=data||[];render()}
function card(a){const mine=a.owner_id===session?.user?.id;return `<article class="activity"><div><span class="tag">${esc(a.activity_type)}</span><h4>${esc(a.title)}</h4><p>${fmt(a.activity_date)} · ${esc(a.professor_name)}</p>${visitorMode&&a.description?`<p class="activity-description">${esc(a.description)}</p>`:''}<div class="activity-meta">${a.participants!=null?`<span>${a.participants} participantes</span>`:''}${a.duration_hours!=null?`<span>${a.duration_hours} h</span>`:''}</div></div>${!visitorMode&&(mine||profile?.is_admin)?`<div class="activity-actions"><button data-delete="${a.id}" aria-label="Excluir ${esc(a.title)}">Excluir</button></div>`:''}</article>`}
function render(){const total=items.length,participants=items.reduce((s,a)=>s+(a.participants||0),0),hours=items.reduce((s,a)=>s+Number(a.duration_hours||0),0);$('#stat-total').textContent=total;$('#stat-participants').textContent=participants.toLocaleString('pt-BR');$('#stat-hours').textContent=`${hours.toLocaleString('pt-BR')} h`;$('#recent-list').innerHTML=total?items.slice(0,5).map(card).join(''):'<div class="empty">Ainda não há atividades registradas.</div>';filterList();bindDeletes()}
function filterList(){const q=$('#search').value.trim().toLowerCase(),type=$('#filter-type').value;const filtered=items.filter(a=>(!type||a.activity_type===type)&&(!q||a.title.toLowerCase().includes(q)||a.professor_name.toLowerCase().includes(q)));$('#all-list').innerHTML=filtered.length?filtered.map(card).join(''):'<div class="empty">Nenhuma atividade encontrada.</div>';bindDeletes()}
$('#search').oninput=filterList;$('#filter-type').onchange=filterList;
function bindDeletes(){$$('[data-delete]').forEach(b=>b.onclick=async()=>{if(!confirm('Excluir esta atividade?'))return;const {error}=await db.from('activities').delete().eq('id',b.dataset.delete);if(error)return toast('Não foi possível excluir.',true);toast('Atividade excluída.');await loadActivities()})}

function reportItems(){const type=$('#report-type').value,from=$('#report-from').value,to=$('#report-to').value;return items.filter(a=>(!type||a.activity_type===type)&&(!from||a.activity_date>=from)&&(!to||a.activity_date<=to))}
function groupReport(rows){const groups={};rows.forEach(a=>{const key=a.activity_type||'Outro';groups[key]||={type:key,count:0,hours:0};groups[key].count++;groups[key].hours+=Number(a.duration_hours||0)});return Object.values(groups).sort((a,b)=>b.count-a.count||a.type.localeCompare(b.type,'pt-BR'))}
function bars(groups,key,suffix){if(!groups.length)return '<div class="empty">Sem dados para os filtros selecionados.</div>';const max=Math.max(...groups.map(g=>g[key]),1);return groups.map(g=>`<div class="bar-row"><span title="${esc(g.type)}">${esc(g.type)}</span><div class="bar-track"><i style="width:${Math.max((g[key]/max)*100,g[key]?3:0)}%"></i></div><strong>${Number(g[key]).toLocaleString('pt-BR')}${suffix}</strong></div>`).join('')}
function renderReport(){const rows=reportItems(),groups=groupReport(rows),participants=rows.reduce((s,a)=>s+Number(a.participants||0),0),hours=rows.reduce((s,a)=>s+Number(a.duration_hours||0),0);$('#report-total').textContent=rows.length.toLocaleString('pt-BR');$('#report-participants').textContent=participants.toLocaleString('pt-BR');$('#report-hours').textContent=hours.toLocaleString('pt-BR');$('#chart-count').innerHTML=bars(groups,'count','');$('#chart-hours').innerHTML=bars(groups,'hours',' h');$('#report-result-count').textContent=`${rows.length.toLocaleString('pt-BR')} ${rows.length===1?'atividade':'atividades'}`;$('#report-generated-at').textContent=`Gerado em ${new Date().toLocaleDateString('pt-BR')}`;$('#report-table').innerHTML=rows.length?rows.map(a=>`<tr><td>${fmt(a.activity_date)}</td><td>${esc(a.title)}</td><td>${esc(a.activity_type)}</td><td>${esc(a.professor_name)}</td><td class="number">${a.participants??'—'}</td><td class="number">${a.duration_hours??'—'}</td></tr>`).join(''):'<tr><td colspan="6" class="table-empty">Nenhuma atividade encontrada com os filtros atuais.</td></tr>';$('#download-csv').disabled=!rows.length;$('#download-pdf').disabled=!rows.length}
['#report-type','#report-from','#report-to'].forEach(id=>$(id).onchange=renderReport);
function csvCell(value){const text=String(value??'');return /[",\n]/.test(text)?`"${text.replace(/"/g,'""')}"`:text}
$('#download-csv').onclick=()=>{const rows=reportItems();if(!rows.length)return;const header=['Data','Título','Tipo','Professor','Participantes','Carga Horária (h)','Produto'];const body=rows.map(a=>[fmt(a.activity_date),a.title,a.activity_type,a.professor_name,a.participants??0,a.duration_hours??0,a.has_product?(a.product_type||'Sim'):'Não']);const csv='\uFEFF'+[header,...body].map(row=>row.map(csvCell).join(',')).join('\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));const link=document.createElement('a');link.href=url;link.download='relatorio_atividades_decb.csv';link.click();URL.revokeObjectURL(url)};
function printReport(pdf=false){document.body.classList.toggle('pdf-export',pdf);window.print();setTimeout(()=>document.body.classList.remove('pdf-export'),500)}
$('#print-report').onclick=()=>printReport(false);
$('#download-pdf').onclick=()=>{toast('Na janela seguinte, escolha “Salvar como PDF”.');setTimeout(()=>printReport(true),300)};

function updateProductFields(){const has=$('input[name="hasProduct"]:checked').value==='true',type=$('#product-type').value,detail=$('#product-detail');$('#product-fields').classList.toggle('hidden',!has);$('#product-type').required=has;detail.required=has&&Boolean(type);$('#product-detail-label').textContent=type==='Virtual'?'Endereço eletrônico (URL)':'Localização do produto';detail.type=type==='Virtual'?'url':'text';detail.placeholder=type==='Virtual'?'https://…':'Ex.: Laboratório de Botânica, armário 3';if(!has){$('#product-type').value='';detail.value='';detail.required=false}}
$$('input[name="hasProduct"]').forEach(r=>r.onchange=updateProductFields);
$('#product-type').onchange=updateProductFields;
$('#clear-activity').onclick=()=>{if(!confirm('Limpar todos os campos deste formulário?'))return;$('#activity-form').reset();$('#date').value=new Date().toISOString().slice(0,10);$('#professor').value=profile?.full_name||'';updateProductFields()};
async function upload(file,kind){if(!file)return null;if(file.size>10*1024*1024)throw new Error('Cada anexo deve ter no máximo 10 MB.');const safe=file.name.replace(/[^a-zA-Z0-9._-]/g,'_');const path=`${session.user.id}/${crypto.randomUUID()}-${safe}`;const {error}=await db.storage.from('activity-attachments').upload(path,file,{contentType:file.type,upsert:false});if(error)throw error;return path}

$('#activity-form').onsubmit=async e=>{e.preventDefault();const btn=$('#save-activity');btn.disabled=true;btn.textContent='Salvando…';try{const has=$('input[name="hasProduct"]:checked').value==='true',pt=has?$('#product-type').value:null,detail=$('#product-detail').value.trim();if(has&&!pt)throw new Error('Selecione o tipo de produto.');if(has&&!detail)throw new Error(pt==='Virtual'?'Informe o endereço eletrônico do produto.':'Informe a localização do produto.');const [photoPath,pdfPath]=await Promise.all([upload($('#photo').files[0],'photo'),upload($('#pdf').files[0],'pdf')]);const payload={title:$('#title').value.trim(),activity_type:$('#type').value,activity_date:$('#date').value,professor_name:profile.full_name,professor_email:session.user.email.toLowerCase(),description:$('#description').value.trim(),participants:$('#participants').value?Number($('#participants').value):null,duration_hours:$('#duration').value?Number($('#duration').value):null,has_product:has,product_type:pt,product_location:has&&pt==='Físico'?detail:null,product_url:has&&pt==='Virtual'?detail:null,photo_path:photoPath,pdf_path:pdfPath};const {error}=await db.from('activities').insert(payload);if(error)throw error;toast('Atividade registrada com sucesso.');e.target.reset();$('#date').value=new Date().toISOString().slice(0,10);$('#professor').value=profile.full_name;updateProductFields();await loadActivities();showPage('dashboard')}catch(err){toast(err.message||'Não foi possível salvar.',true)}finally{btn.disabled=false;btn.textContent='Registrar atividade'}};

$('#open-citation').onclick=()=>$('#citation-dialog').showModal();
$('#copy-citation').onclick=async()=>{try{await navigator.clipboard.writeText($('#citation-text').textContent.trim());toast('Referência copiada.')}catch{toast('Não foi possível copiar automaticamente.',true)}};

if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js'));
