const SUPABASE_URL='https://mjyuwmqnmzdhpvpnvsik.supabase.co';
const SUPABASE_KEY='sb_publishable_JeT3zymWaxbpQezfudnQWw_QLQvrLyw';
const db=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
const PUBLIC_URL='https://egbertomesquita-cmd.github.io/registro-atividades-decb/';
let session=null,profile=null,items=[],visitorMode=false,editingActivity=null;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const toast=(message,error=false)=>{const el=$('#toast');el.textContent=message;el.className=error?'show error':'show';setTimeout(()=>el.className='',3500)};
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const externalLinksField=document.createElement('div');externalLinksField.className='field span-2';externalLinksField.innerHTML='<label for="external-links">Links de materiais (opcional)</label><textarea id="external-links" rows="4" maxlength="20000" placeholder="https://drive.google.com/…&#10;https://onedrive.live.com/…"></textarea><small>Inclua um link por linha, até 10 links. Google Drive, OneDrive ou outro serviço. Os arquivos permanecem no serviço de origem; configure o compartilhamento para o público desejado. Os links ficam visíveis na consulta pública desta atividade.</small>';$('#photo').closest('.section-grid').append(externalLinksField);
function parseExternalLinks(text){const links=text.split(/\r?\n/).map(s=>s.trim()).filter(Boolean);if(links.length>10)throw Error('Inclua no máximo 10 links de materiais.');return [...new Set(links.map(value=>{let url;try{url=new URL(value)}catch{throw Error('Informe links completos, começando com https:// ou http://.')}if(!['https:','http:'].includes(url.protocol)||url.username||url.password||value.length>2000)throw Error('Use links HTTP ou HTTPS, sem usuário e senha no endereço.');return url.href}))]}
function renderExternalLinks(a){let section=document.getElementById('activity-external-links');if(!section){section=document.createElement('section');section.id='activity-external-links';section.className='detail-section';$('#activity-documents').parentElement.after(section)}section.replaceChildren();const heading=document.createElement('h3');heading.textContent='Materiais por link';section.append(heading);const links=Array.isArray(a.external_links)?a.external_links:[];if(!links.length){const p=document.createElement('p');p.textContent='Nenhum link de material informado.';section.append(p);return}for(const [i,value] of links.entries()){const href=safeWebUrl(value);if(!href)continue;const p=document.createElement('p'),link=document.createElement('a');link.href=href;link.target='_blank';link.rel='noopener noreferrer';link.className='document-link';link.textContent='Abrir material '+(i+1)+' · '+new URL(href).hostname;p.append(link);section.append(p)}}
const fmt=d=>new Date(d+'T12:00:00').toLocaleDateString('pt-BR');

$('#google-login').onclick=async()=>{const btn=$('#google-login');btn.disabled=true;try{const {error}=await db.auth.signInWithOAuth({provider:'google',options:{redirectTo:PUBLIC_URL}});if(error)throw error}catch(err){toast(err.message||'Não foi possível iniciar o acesso pelo Google.',true);btn.disabled=false}};

async function authorize(userSession){visitorMode=false;document.body.classList.remove('public-mode');session=userSession;const email=session.user.email.toLowerCase();const {data,error}=await db.from('authorized_users').select('full_name,is_admin,active').eq('email',email).maybeSingle();if(error||!data?.active){await db.auth.signOut();session=null;throw new Error('Este e-mail não está na lista de acesso do DECB.')}profile=data;$('#user-name').textContent=data.full_name;$('#user-email').textContent=email;$('#professor').value=data.full_name;$('#logout').textContent='Sair';$('#auth-view').classList.add('hidden');$('#app-view').classList.remove('hidden');await loadActivities();}

db.auth.onAuthStateChange(async(_event,newSession)=>{if(newSession){try{await authorize(newSession)}catch(err){toast(err.message,true)}}else if(!visitorMode){$('#app-view').classList.add('hidden');$('#auth-view').classList.remove('hidden')}});
$('#public-access').onclick=async()=>{visitorMode=true;session=null;profile=null;document.body.classList.add('public-mode');$('#user-name').textContent='Visitante';$('#user-email').textContent='Consulta pública';$('#logout').textContent='Voltar ao acesso';$('#observer-note').classList.remove('hidden');$('#auth-view').classList.add('hidden');$('#app-view').classList.remove('hidden');await loadActivities();showPage('activities')};
$('#logout').onclick=()=>{if(visitorMode){visitorMode=false;document.body.classList.remove('public-mode');$('#observer-note').classList.add('hidden');$('#app-view').classList.add('hidden');$('#auth-view').classList.remove('hidden');return}db.auth.signOut()};

function showPage(id){$$('.page').forEach(p=>p.classList.toggle('hidden',p.id!==id));$$('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===id));$('.sidebar').classList.remove('open');if(id==='register'){$('#date').value||=new Date().toISOString().slice(0,10);$('#professor').value=editingActivity?.professor_name||profile?.full_name||''}if(id==='reports')renderReport()}
$$('[data-view]').forEach(b=>b.onclick=()=>{if(b.dataset.view==='register')resetActivityForm();showPage(b.dataset.view)});$$('[data-go]').forEach(b=>b.onclick=()=>{resetActivityForm();showPage(b.dataset.go)});$('#menu').onclick=()=>$('.sidebar').classList.toggle('open');

async function loadActivities(){const columns=visitorMode?'id,title,activity_type,activity_date,professor_name,description,participants,duration_hours,has_product,product_type,product_location,product_url,photo_path,pdf_path,external_links':'*';const {data,error}=await db.from('activities').select(columns).order('activity_date',{ascending:false}).order('created_at',{ascending:false});if(error)return toast(visitorMode?'A consulta pública ainda não está disponível.':'Não foi possível carregar as atividades.',true);items=data||[];render()}
function card(a){const mine=a.owner_id===session?.user?.id,hasMedia=a.external_links?.length||a.photo_path||a.pdf_path||a.product_url||a.product_location;return `<article class="activity"><div><span class="tag">${esc(a.activity_type)}</span><h4>${esc(a.title)}</h4><p>${fmt(a.activity_date)} · ${esc(a.professor_name)}</p>${visitorMode&&a.description?`<p class="activity-description">${esc(a.description)}</p>`:''}<div class="activity-meta">${a.participants!=null?`<span>${a.participants} participantes</span>`:''}${a.duration_hours!=null?`<span>${a.duration_hours} h</span>`:''}${hasMedia?'<span>Possui produto ou anexo</span>':''}</div></div><div class="activity-actions"><button class="view-activity" data-view-activity="${a.id}" aria-label="Ver detalhes e anexos de ${esc(a.title)}">Ver detalhes</button>${!visitorMode&&(mine||profile?.is_admin)?`<button data-edit="${a.id}" aria-label="Editar ${esc(a.title)}">Editar</button><button data-delete="${a.id}" aria-label="Excluir ${esc(a.title)}">Excluir</button>`:''}</div></article>`}
function render(){const total=items.length,participants=items.reduce((s,a)=>s+(a.participants||0),0),hours=items.reduce((s,a)=>s+Number(a.duration_hours||0),0);$('#stat-total').textContent=total;$('#stat-participants').textContent=participants.toLocaleString('pt-BR');$('#stat-hours').textContent=`${hours.toLocaleString('pt-BR')} h`;$('#recent-list').innerHTML=total?items.slice(0,5).map(card).join(''):'<div class="empty">Ainda não há atividades registradas.</div>';filterList();bindDeletes()}
function filterList(){const q=$('#search').value.trim().toLowerCase(),type=$('#filter-type').value;const filtered=items.filter(a=>(!type||a.activity_type===type)&&(!q||a.title.toLowerCase().includes(q)||a.professor_name.toLowerCase().includes(q)));$('#all-list').innerHTML=filtered.length?filtered.map(card).join(''):'<div class="empty">Nenhuma atividade encontrada.</div>';bindDeletes()}
$('#search').oninput=filterList;$('#filter-type').onchange=filterList;
function bindDeletes(){$('[data-edit]').forEach(b=>b.onclick=()=>editActivity(Number(b.dataset.edit)));$$('[data-view-activity]').forEach(b=>b.onclick=()=>openActivity(Number(b.dataset.viewActivity)));$$('[data-delete]').forEach(b=>b.onclick=async()=>{if(!confirm('Excluir esta atividade?'))return;const {error}=await db.from('activities').delete().eq('id',b.dataset.delete);if(error)return toast('Não foi possível excluir.',true);toast('Atividade excluída.');await loadActivities()})}

async function signedAttachment(path,download=false){if(!path)return null;const {data,error}=await db.storage.from('activity-attachments').createSignedUrl(path,600,download?{download:true}:undefined);if(error)throw error;return data.signedUrl}
function safeWebUrl(value){try{const url=new URL(value);return ['http:','https:'].includes(url.protocol)?url.href:null}catch{return null}}
async function openActivity(id){const a=items.find(item=>Number(item.id)===id);if(!a)return;$('#activity-detail-title').textContent=a.title;$('#activity-detail-meta').textContent=`${fmt(a.activity_date)} · ${a.activity_type} · ${a.professor_name}`;$('#activity-detail-description').textContent=a.description||'Sem descrição.';const product=$('#activity-product'),gallery=$('#activity-gallery'),documents=$('#activity-documents');product.replaceChildren();gallery.innerHTML='<p class="media-loading">Carregando galeria…</p>';documents.replaceChildren();if(a.has_product){const link=safeWebUrl(a.product_url);const p=document.createElement('p');p.textContent=a.product_type==='Virtual'?'Produto virtual':'Produto físico';product.append(p);if(link){const anchor=document.createElement('a');anchor.href=link;anchor.target='_blank';anchor.rel='noopener';anchor.textContent='Acessar produto';product.append(anchor)}else if(a.product_location){const location=document.createElement('span');location.textContent=a.product_location;product.append(location)}}else product.innerHTML='<p>Nenhum produto informado.</p>';renderExternalLinks(a);$('#activity-detail-dialog').showModal();try{const [photoUrl,pdfUrl]=await Promise.all([signedAttachment(a.photo_path),signedAttachment(a.pdf_path,true)]);gallery.replaceChildren();if(photoUrl){const link=document.createElement('a');link.href=photoUrl;link.target='_blank';link.rel='noopener';link.className='gallery-item';const image=document.createElement('img');image.src=photoUrl;image.alt=`Foto da atividade ${a.title}`;link.append(image);gallery.append(link)}else gallery.innerHTML='<p class="media-empty">Nenhuma imagem registrada nesta atividade.</p>';if(pdfUrl){const link=document.createElement('a');link.href=pdfUrl;link.target='_blank';link.rel='noopener';link.className='document-link';link.textContent='Abrir ou baixar documento PDF';documents.append(link)}else documents.innerHTML='<p class="media-empty">Nenhum PDF registrado nesta atividade.</p>'}catch(err){gallery.innerHTML='<p class="media-error">Não foi possível carregar os anexos.</p>';documents.innerHTML='<p class="media-error">Tente novamente em alguns instantes.</p>';toast(err.message||'Não foi possível abrir os anexos.',true)}}

function reportItems(){const type=$('#report-type').value,from=$('#report-from').value,to=$('#report-to').value;return items.filter(a=>(!type||a.activity_type===type)&&(!from||a.activity_date>=from)&&(!to||a.activity_date<=to))}
function groupReport(rows){const groups={};rows.forEach(a=>{const key=a.activity_type||'Outro';groups[key]||={type:key,count:0,hours:0};groups[key].count++;groups[key].hours+=Number(a.duration_hours||0)});return Object.values(groups).sort((a,b)=>b.count-a.count||a.type.localeCompare(b.type,'pt-BR'))}
function bars(groups,key,suffix){if(!groups.length)return '<div class="empty">Sem dados para os filtros selecionados.</div>';const max=Math.max(...groups.map(g=>g[key]),1);return groups.map(g=>`<div class="bar-row"><span title="${esc(g.type)}">${esc(g.type)}</span><div class="bar-track"><i style="width:${Math.max((g[key]/max)*100,g[key]?3:0)}%"></i></div><strong>${Number(g[key]).toLocaleString('pt-BR')}${suffix}</strong></div>`).join('')}
function renderReport(){const rows=reportItems(),groups=groupReport(rows),participants=rows.reduce((s,a)=>s+Number(a.participants||0),0),hours=rows.reduce((s,a)=>s+Number(a.duration_hours||0),0);$('#report-total').textContent=rows.length.toLocaleString('pt-BR');$('#report-participants').textContent=participants.toLocaleString('pt-BR');$('#report-hours').textContent=hours.toLocaleString('pt-BR');$('#chart-count').innerHTML=bars(groups,'count','');$('#chart-hours').innerHTML=bars(groups,'hours',' h');$('#report-result-count').textContent=`${rows.length.toLocaleString('pt-BR')} ${rows.length===1?'atividade':'atividades'}`;$('#report-generated-at').textContent=`Gerado em ${new Date().toLocaleDateString('pt-BR')}`;$('#report-table').innerHTML=rows.length?rows.map(a=>`<tr><td>${fmt(a.activity_date)}</td><td>${esc(a.title)}</td><td>${esc(a.activity_type)}</td><td>${esc(a.professor_name)}</td><td class="number">${a.participants??'—'}</td><td class="number">${a.duration_hours??'—'}</td></tr>`).join(''):'<tr><td colspan="6" class="table-empty">Nenhuma atividade encontrada com os filtros atuais.</td></tr>';$('#download-csv').disabled=!rows.length;$('#download-pdf').disabled=!rows.length}
['#report-type','#report-from','#report-to'].forEach(id=>$(id).onchange=renderReport);
function csvCell(value){const text=String(value??'');return /[",\n]/.test(text)?`"${text.replace(/"/g,'""')}"`:text}
$('#download-csv').onclick=()=>{const rows=reportItems();if(!rows.length)return;const header=['Data','Título','Tipo','Professor','Participantes','Carga Horária (h)','Produto'];const body=rows.map(a=>[fmt(a.activity_date),a.title,a.activity_type,a.professor_name,a.participants??0,a.duration_hours??0,a.has_product?(a.product_type||'Sim'):'Não']);const csv='\uFEFF'+[header,...body].map(row=>row.map(csvCell).join(',')).join('\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));const link=document.createElement('a');link.href=url;link.download='relatorio_atividades_decb.csv';link.click();URL.revokeObjectURL(url)};
function printReport(pdf=false){document.body.classList.toggle('pdf-export',pdf);window.print();setTimeout(()=>document.body.classList.remove('pdf-export'),500)}
$('#print-report').onclick=()=>printReport(false);
$('#download-pdf').onclick=()=>{toast('Na janela seguinte, escolha “Salvar como PDF”.');setTimeout(()=>printReport(true),300)};

function updateProductFields(){const has=$('input[name="hasProduct"]:checked').value==='true',type=$('#product-type').value,detail=$('#product-detail');$('#product-fields').classList.toggle('hidden',!has);$('#product-type').required=has;detail.required=has&&Boolean(type);$('#product-detail-label').textContent=type==='Virtual'?'Endereço eletrônico (URL)':'Localização do produto';detail.type=type==='Virtual'?'url':'text';detail.placeholder=type==='Virtual'?'https://…':'Ex.: Laboratório de Botânica, armário 3';if(!has){$('#product-type').value='';detail.value='';detail.required=false}}
$$('input[name="hasProduct"]').forEach(r=>r.onchange=updateProductFields);
$('#product-type').onchange=updateProductFields;
function canEditActivity(a){return !visitorMode&&!!session&&!!profile&&(a.owner_id===session.user.id||profile.is_admin)}
function updateEditLabels(){const editing=!!editingActivity;$('#register .eyebrow').textContent=editing?'EDITAR PUBLICAÇÃO':'NOVO REGISTRO';$('#register h2').textContent=editing?'Editar atividade':'Registrar atividade';$('#register .page-head p:last-child').textContent=editing?'As alterações serão aplicadas à atividade publicada. Anexos existentes são mantidos se você não selecionar novos arquivos.':'Preencha o formulário abaixo para registrar uma nova atividade acadêmica.';$('#save-activity').textContent=editing?'Salvar alterações':'Registrar atividade';for(const [field,path] of [['photo','photo_path'],['pdf','pdf_path']]){let hint=document.getElementById(field+'-current');if(!hint){hint=document.createElement('small');hint.id=field+'-current';$('#'+field).parentElement.append(hint)}hint.textContent=editingActivity?.[path]?'Anexo atual mantido. Escolha outro arquivo para substituí-lo.':''}}
function resetActivityForm(){editingActivity=null;$('#activity-form').reset();$('#date').value=new Date().toISOString().slice(0,10);$('#professor').value=profile?.full_name||'';updateProductFields();updateEditLabels()}
function editActivity(id){const a=items.find(item=>Number(item.id)===id);if(!a||!canEditActivity(a))return toast('Você não tem permissão para editar esta atividade.',true);resetActivityForm();editingActivity={...a};$('#external-links').value=(a.external_links||[]).join('\n');for(const [field,key] of Object.entries({title:'title',type:'activity_type',date:'activity_date',professor:'professor_name',description:'description',participants:'participants',duration:'duration_hours'}))$('#'+field).value=a[key]??'';$('input[name="hasProduct"][value="'+Boolean(a.has_product)+'"]').checked=true;$('#product-type').value=a.product_type||'';updateProductFields();$('#product-detail').value=a.product_type==='Virtual'?(a.product_url||''):(a.product_location||'');updateEditLabels();showPage('register');$('#title').focus()}
$('#clear-activity').onclick=()=>{if(!confirm(editingActivity?'Descartar alterações e recarregar a atividade publicada?':'Limpar todos os campos deste formulário?'))return;if(editingActivity)editActivity(editingActivity.id);else resetActivityForm()};
async function upload(file,kind){if(!file)return null;if(file.size>10*1024*1024)throw new Error('Cada anexo deve ter no máximo 10 MB.');const safe=file.name.replace(/[^a-zA-Z0-9._-]/g,'_');const path=`${session.user.id}/${crypto.randomUUID()}-${safe}`;const {error}=await db.storage.from('activity-attachments').upload(path,file,{contentType:file.type,upsert:false});if(error)throw error;return path}

$('#activity-form').onsubmit=async e=>{
 e.preventDefault();const original=editingActivity;if(visitorMode||!session||!profile||(original&&!canEditActivity(original)))return toast('Entre com uma conta autorizada para salvar.',true);
 const btn=$('#save-activity');btn.disabled=true;btn.textContent='Salvando…';
 try{
 const has=$('input[name="hasProduct"]:checked').value==='true',pt=has?$('#product-type').value:null,detail=$('#product-detail').value.trim();
 if(has&&!pt)throw Error('Selecione o tipo de produto.');if(has&&!detail)throw Error(pt==='Virtual'?'Informe o endereço eletrônico do produto.':'Informe a localização do produto.');
 const externalLinks=parseExternalLinks($('#external-links').value);
 const photoFile=$('#photo').files[0],pdfFile=$('#pdf').files[0];
 for(const file of [photoFile,pdfFile])if(file&&file.size>10*1024*1024)throw Error('Cada anexo deve ter no máximo 10 MB.');
 const photoPath=photoFile?await upload(photoFile,'photo'):(original?.photo_path||null);
 const pdfPath=pdfFile?await upload(pdfFile,'pdf'):(original?.pdf_path||null);
 const payload={title:$('#title').value.trim(),activity_type:$('#type').value,activity_date:$('#date').value,description:$('#description').value.trim(),participants:$('#participants').value?Number($('#participants').value):null,duration_hours:$('#duration').value?Number($('#duration').value):null,has_product:has,product_type:pt,product_location:has&&pt==='Físico'?detail:null,product_url:has&&pt==='Virtual'?detail:null,photo_path:photoPath,pdf_path:pdfPath,external_links:externalLinks};
 let result;
 if(original){let query=db.from('activities').update({...payload,updated_at:new Date().toISOString()}).eq('id',original.id);if(original.updated_at)query=query.eq('updated_at',original.updated_at);result=await query.select('id').maybeSingle();if(!result.error&&!result.data)throw Error('A atividade foi alterada por outra pessoa ou você não tem mais permissão. Reabra o registro antes de editar.');}
 else result=await db.from('activities').insert({...payload,professor_name:profile.full_name,professor_email:session.user.email.toLowerCase()});
 if(result.error)throw result.error;
 toast(original?'Atividade atualizada com sucesso.':'Atividade registrada com sucesso.');resetActivityForm();await loadActivities();showPage(original?'activities':'dashboard');
 }catch(err){toast(err.message||'Não foi possível salvar. Seus campos foram mantidos.',true)}finally{btn.disabled=false;updateEditLabels()}
};

$('#open-citation').onclick=()=>$('#citation-dialog').showModal();
$('#copy-citation').onclick=async()=>{try{await navigator.clipboard.writeText($('#citation-text').textContent.trim());toast('Referência copiada.')}catch{toast('Não foi possível copiar automaticamente.',true)}};

if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js'));